### ISSUE TITLE
US4 - No se muestra el id del curso ni el nombre de la materia en selector de curso

### ISSUE THREAD

**Issue by OsirisArguello** [OsirisArguello/QuechuaApp#67]
Pasos para reproducir:
-Me logueo en el admin
-Presiono en la opción Acciones del menu superior
-Selecciono la opcion Horario Cursada
-Presiono la opción Crear Horario Cursada
Comportamiento Esperado:
Aparecen una lista de Cursos en estado Activo, ordenados por id de curso, cada curso se describe con su codigo de materia, nombre de materia, nombre del profesor y id de curso
Comportamiento Actual:
Solo aparece el codigo de la materia y el nombre del profesor

**Comment by dkux** [comment]
No aplica más
